module ClickHaskell.Native.Versioning where

import ClickHaskell.DbTypes (ChUInt64)

type ProtocolRevision = ChUInt64

_DBMS_MIN_REVISION_WITH_CLIENT_INFO :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_CLIENT_INFO = 54032;

_DBMS_MIN_REVISION_WITH_SERVER_TIMEZONE :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_SERVER_TIMEZONE = 54058;

_DBMS_MIN_REVISION_WITH_QUOTA_KEY_IN_CLIENT_INFO :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_QUOTA_KEY_IN_CLIENT_INFO = 54060;

_DBMS_MIN_REVISION_WITH_TABLES_STATUS :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_TABLES_STATUS = 54226;

_DBMS_MIN_REVISION_WITH_TIME_ZONE_PARAMETER_IN_DATETIME_DATA_TYPE :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_TIME_ZONE_PARAMETER_IN_DATETIME_DATA_TYPE = 54337;

_DBMS_MIN_REVISION_WITH_SERVER_DISPLAY_NAME :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_SERVER_DISPLAY_NAME = 54372;

_DBMS_MIN_REVISION_WITH_VERSION_PATCH :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_VERSION_PATCH = 54401;

_DBMS_MIN_REVISION_WITH_SERVER_LOGS :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_SERVER_LOGS = 54406;

-- Minimum revision with exactly the same set of aggregation methods and rules to select them.
-- Two-level (bucketed) aggregation is incompatible if servers are inconsistent in these rules
-- (keys will be placed in different buckets and result will not be fully aggregated).
_DBMS_MIN_REVISION_WITH_CURRENT_AGGREGATION_VARIANT_SELECTION_METHOD :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_CURRENT_AGGREGATION_VARIANT_SELECTION_METHOD = 54448;

_DBMS_MIN_MAJOR_VERSION_WITH_CURRENT_AGGREGATION_VARIANT_SELECTION_METHOD :: ProtocolRevision
_DBMS_MIN_MAJOR_VERSION_WITH_CURRENT_AGGREGATION_VARIANT_SELECTION_METHOD = 21;

_DBMS_MIN_MINOR_VERSION_WITH_CURRENT_AGGREGATION_VARIANT_SELECTION_METHOD :: ProtocolRevision
_DBMS_MIN_MINOR_VERSION_WITH_CURRENT_AGGREGATION_VARIANT_SELECTION_METHOD = 4;

_DBMS_MIN_REVISION_WITH_COLUMN_DEFAULTS_METADATA :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_COLUMN_DEFAULTS_METADATA = 54410;

_DBMS_MIN_REVISION_WITH_LOW_CARDINALITY_TYPE :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_LOW_CARDINALITY_TYPE = 54405;

_DBMS_MIN_REVISION_WITH_CLIENT_WRITE_INFO :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_CLIENT_WRITE_INFO = 54420;

-- Minimum revision supporting SettingsBinaryFormat::STRINGS.
_DBMS_MIN_REVISION_WITH_SETTINGS_SERIALIZED_AS_STRINGS :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_SETTINGS_SERIALIZED_AS_STRINGS = 54429;

_DBMS_MIN_REVISION_WITH_SCALARS :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_SCALARS = 54429;

-- Minimum revision supporting OpenTelemetry
_DBMS_MIN_REVISION_WITH_OPENTELEMETRY :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_OPENTELEMETRY = 54442;

_DBMS_MIN_REVISION_WITH_AGGREGATE_FUNCTIONS_VERSIONING :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_AGGREGATE_FUNCTIONS_VERSIONING = 54452;

_DBMS_CLUSTER_PROCESSING_PROTOCOL_VERSION :: ProtocolRevision
_DBMS_CLUSTER_PROCESSING_PROTOCOL_VERSION = 1;

_DBMS_MIN_SUPPORTED_PARALLEL_REPLICAS_PROTOCOL_VERSION :: ProtocolRevision
_DBMS_MIN_SUPPORTED_PARALLEL_REPLICAS_PROTOCOL_VERSION = 3;

_DBMS_PARALLEL_REPLICAS_MIN_VERSION_WITH_MARK_SEGMENT_SIZE_FIELD :: ProtocolRevision
_DBMS_PARALLEL_REPLICAS_MIN_VERSION_WITH_MARK_SEGMENT_SIZE_FIELD = 4;

_DBMS_PARALLEL_REPLICAS_PROTOCOL_VERSION :: ProtocolRevision
_DBMS_PARALLEL_REPLICAS_PROTOCOL_VERSION = 4;

_DBMS_MIN_REVISION_WITH_PARALLEL_REPLICAS :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_PARALLEL_REPLICAS = 54453;

_DBMS_MERGE_TREE_PART_INFO_VERSION :: ProtocolRevision
_DBMS_MERGE_TREE_PART_INFO_VERSION = 1;

_DBMS_MIN_REVISION_WITH_INTERSERVER_SECRET :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_INTERSERVER_SECRET = 54441;

_DBMS_MIN_REVISION_WITH_X_FORWARDED_FOR_IN_CLIENT_INFO :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_X_FORWARDED_FOR_IN_CLIENT_INFO = 54443;

_DBMS_MIN_REVISION_WITH_REFERER_IN_CLIENT_INFO :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_REFERER_IN_CLIENT_INFO = 54447;

_DBMS_MIN_PROTOCOL_VERSION_WITH_DISTRIBUTED_DEPTH :: ProtocolRevision
_DBMS_MIN_PROTOCOL_VERSION_WITH_DISTRIBUTED_DEPTH = 54448;

_DBMS_MIN_PROTOCOL_VERSION_WITH_INCREMENTAL_PROFILE_EVENTS :: ProtocolRevision
_DBMS_MIN_PROTOCOL_VERSION_WITH_INCREMENTAL_PROFILE_EVENTS = 54451;

_DBMS_MIN_REVISION_WITH_CUSTOM_SERIALIZATION :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_CUSTOM_SERIALIZATION = 54454;

_DBMS_MIN_PROTOCOL_VERSION_WITH_INITIAL_QUERY_START_TIME :: ProtocolRevision
_DBMS_MIN_PROTOCOL_VERSION_WITH_INITIAL_QUERY_START_TIME = 54449;

_DBMS_MIN_PROTOCOL_VERSION_WITH_PROFILE_EVENTS_IN_INSERT :: ProtocolRevision
_DBMS_MIN_PROTOCOL_VERSION_WITH_PROFILE_EVENTS_IN_INSERT = 54456;

_DBMS_MIN_PROTOCOL_VERSION_WITH_VIEW_IF_PERMITTED :: ProtocolRevision
_DBMS_MIN_PROTOCOL_VERSION_WITH_VIEW_IF_PERMITTED = 54457;

_DBMS_MIN_PROTOCOL_VERSION_WITH_ADDENDUM :: ProtocolRevision
_DBMS_MIN_PROTOCOL_VERSION_WITH_ADDENDUM = 54458;

_DBMS_MIN_PROTOCOL_VERSION_WITH_QUOTA_KEY :: ProtocolRevision
_DBMS_MIN_PROTOCOL_VERSION_WITH_QUOTA_KEY = 54458;

_DBMS_MIN_PROTOCOL_VERSION_WITH_PARAMETERS :: ProtocolRevision
_DBMS_MIN_PROTOCOL_VERSION_WITH_PARAMETERS = 54459;

-- The server will send query elapsed run time in the Progress packet.
_DBMS_MIN_PROTOCOL_VERSION_WITH_SERVER_QUERY_TIME_IN_PROGRESS :: ProtocolRevision
_DBMS_MIN_PROTOCOL_VERSION_WITH_SERVER_QUERY_TIME_IN_PROGRESS = 54460;

_DBMS_MIN_PROTOCOL_VERSION_WITH_PASSWORD_COMPLEXITY_RULES :: ProtocolRevision
_DBMS_MIN_PROTOCOL_VERSION_WITH_PASSWORD_COMPLEXITY_RULES = 54461;

_DBMS_MIN_REVISION_WITH_INTERSERVER_SECRET_V2 :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_INTERSERVER_SECRET_V2 = 54462;

_DBMS_MIN_PROTOCOL_VERSION_WITH_TOTAL_BYTES_IN_PROGRESS :: ProtocolRevision
_DBMS_MIN_PROTOCOL_VERSION_WITH_TOTAL_BYTES_IN_PROGRESS = 54463;

_DBMS_MIN_PROTOCOL_VERSION_WITH_TIMEZONE_UPDATES :: ProtocolRevision
_DBMS_MIN_PROTOCOL_VERSION_WITH_TIMEZONE_UPDATES = 54464;

_DBMS_MIN_REVISION_WITH_SPARSE_SERIALIZATION :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_SPARSE_SERIALIZATION = 54465;

_DBMS_MIN_REVISION_WITH_SSH_AUTHENTICATION :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_SSH_AUTHENTICATION = 54466;

-- Send read-only flag for Replicated tables as well
_DBMS_MIN_REVISION_WITH_TABLE_READ_ONLY_CHECK :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_TABLE_READ_ONLY_CHECK = 54467;

_DBMS_MIN_REVISION_WITH_SYSTEM_KEYWORDS_TABLE :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_SYSTEM_KEYWORDS_TABLE = 54468;

_DBMS_MIN_REVISION_WITH_ROWS_BEFORE_AGGREGATION :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_ROWS_BEFORE_AGGREGATION = 54469;

-- Packets size header
_DBMS_MIN_PROTOCOL_VERSION_WITH_CHUNKED_PACKETS :: ProtocolRevision
_DBMS_MIN_PROTOCOL_VERSION_WITH_CHUNKED_PACKETS = 54470;

_DBMS_MIN_REVISION_WITH_VERSIONED_PARALLEL_REPLICAS_PROTOCOL :: ProtocolRevision
_DBMS_MIN_REVISION_WITH_VERSIONED_PARALLEL_REPLICAS_PROTOCOL = 54471;

-- Version of ClickHouse TCP protocol.
--
-- Should be incremented manually on protocol changes.
--
-- NOTE: DBMS_TCP_PROTOCOL_VERSION has nothing common with VERSION_REVISION,
-- later is just a number for server version (one number instead of commit SHA)
-- for simplicity (sometimes it may be more convenient in some use cases).
_DBMS_TCP_PROTOCOL_VERSION :: ProtocolRevision
_DBMS_TCP_PROTOCOL_VERSION = 54471;
